//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmayeshgah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventsfeed
    {
        public int event_id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string place { get; set; }
        public string call { get; set; }
        public Nullable<bool> active { get; set; }
        public string deadline { get; set; }
        public Nullable<int> year { get; set; }
        public string descrip { get; set; }
    }
}
