//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmayeshgah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsfeed
    {
        public int news_id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> news_day { get; set; }
        public string link { get; set; }
        public string descrip { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
