//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace azmayeshgah.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perlabEntities : DbContext
    {
        public perlabEntities()
            : base("name=perlabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dataset> datasets { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<publication> publications { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
        public virtual DbSet<@event> events { get; set; }
    }
}
